[13.0][ADD] stock_picking_deliveryslip_subtotals
solvosci/slv-stock pull request #13
Opened 2021-03-09 16:28 UTC by ChristianSantamaria

Adds Sorted by Product ID and add a Subtotal section
Preview:
![imagen](https://user-images.githubusercontent.com/22427989/110503787-d646a500-80fc-11eb-8494-5825b25723d5.png)

2021-03-09 16:50 UTC, dalonsod commented on stock_picking_deliveryslip_subtotals/views/stock_picking_deliveryslip_subtotals.xml
> +                    <span t-esc="sum(o.move_line_ids.filtered(lambda x: x.product_id.id == move_line.move_id.product_id.id).mapped('qty_done'))" t-options="{'widget': 'float', 'precision': decimal_pr
This is inefficient (every line calculates aggregated data that could be obtained once). I'll take a look and try to provide you a better solution

2021-03-10 15:29 UTC, dalonsod requested changes
With the required change, locally tested OK. See comment

2021-03-10 15:31 UTC, dalonsod commented on stock_picking_deliveryslip_subtotals/views/stock_picking_deliveryslip_subtotals.xml
> +                    <t t-if="has_serial_number">
Please fix this:
```suggestion
                    <t t-if="has_serial_number" groups="stock.group_lot_on_delivery_slip">
```
With only `has_serial_number` will not work (picking lines could have lots, but disable their presentation by configuration)

2021-03-10 15:46 UTC, dalonsod approved these changes

2021-03-11 08:19 UTC, dalonsod commented
@lmiguens-solvos could you review?

2021-03-11 09:20 UTC, lmiguens-solvos commented
> @lmiguens-solvos could you review?

The idea is fine. All right.
But could the format of the subtotals be changed? For example, simply with a background? without the line ...
And about sorting ... by product id, wouldn't it be better by name?
This is my example:
![image](https://user-images.githubusercontent.com/41901850/110764456-60088680-8253-11eb-9e59-69330a9fad14.png)

2021-03-11 09:57 UTC, dalonsod commented
> But could the format of the subtotals be changed? For example, simply with a background? without the line ... (maybe it "mixes" a bit with the line below)

OK

> And about sorting ... by product id, wouldn't it be better by name?

I agree... but @lromero-solvos initially said that current sorting should be preserved. Maybe could ask him.

2021-03-11 10:35 UTC, ChristianSantamaria commented
@lmiguens-solvos Done, they have removed the top border and added a `background-color: whitesmoke`. What do you think?
![imagen](https://user-images.githubusercontent.com/22427989/110774103-b975b300-825d-11eb-9c66-e236d4f1e566.png)

2021-03-11 10:45 UTC, lmiguens-solvos commented
> @lmiguens-solvos Done, they have removed the top border and added a `background-color: whitesmoke`. What do you think?
> ![imagen](https://user-images.githubusercontent.com/22427989/110774103-b975b300-825d-11eb-9c66-e236d4f1e566.png)

Perfect! I like it much better

2021-03-11 10:47 UTC, lmiguens-solvos commented
> I agree... but @lromero-solvos initially said that current sorting should be preserved. Maybe we could ask him.

Ok, I thought there was no order and this was chosen. But if there already was, for now we are not going to change it. The customer will think (or not).

2021-03-11 10:47 UTC, lmiguens-solvos approved these changes
LGTM

2021-03-11 10:49 UTC, dalonsod commented
> Ok, I thought there was no order and this was chosen. But if there already was, for now we are not going to change it. The customer will think (or not).

That's OK, no problem changing it if needed later.
@ChristianSantamaria please squash commits

2021-03-11 11:57 UTC, merged

2021-03-11 14:53 UTC, lromero-solvos commented
Hello, everybody

I had indicated that this delivery note had to be ordered as another report. Now I don't remember which one. Now, let it be...