[16.0][ADD] stock_picking_deliver_to
solvosci/slv-stock pull request #135
Opened 2024-06-24 12:50 UTC by IriaAlonso

Add deliver_to text field in stock picking and reports

2024-06-24 14:31 UTC, dalonsod requested changes
See comments

2024-06-24 14:31 UTC, dalonsod commented on stock_picking_deliver_to/views/stock_picking.xml
> +                <field name="deliver_to" />
This field should be hidden when picking is not an outgoing one (use `picking_type_code` picking field for this)

2024-06-24 14:31 UTC, dalonsod commented on stock_picking_deliver_to/reports/stock_picking.xml
> +                <div class="col-auto">
Please hide entire structure when `deliver_to` field is empty, so certain space could be saved when not filled

2024-06-25 08:21 UTC, IriaAlonso commented
@dalonsod

2024-06-25 10:54 UTC, dalonsod commented
Locally tested, I've filled the new field for an outgoing picking and I didn't see it in delivery slip report. Could you check?

2024-06-25 11:22 UTC, IriaAlonso commented
@dalonsod Can you text again?

2024-06-25 11:31 UTC, dalonsod commented
Tested again, "Deliver to" now it's shown. But it's shown for every picking, no matter which type is (incoming or outgoing). Please check:

- Code is wrong, you're not referring to current picking document `o.` , si you are actually accessing an undefined variable.
- The exactly condition is "hide report entire structure when _Deliver To_ field is empty" (see below), not when picking is outgoing (that is exactly the opposite condition in some cases, indeed)

2024-06-25 12:10 UTC, IriaAlonso commented
@dalonsod can you test again?

2024-06-25 12:16 UTC, dalonsod commented
Tested :+1: 

Could you add the following minor improvements:
* For picking tree view, add deliver to field, as `optional="hide"` by default.
* For picking search view, add deliver to field as searchable

2024-06-26 07:32 UTC, IriaAlonso commented
@dalonsod

2024-06-26 12:14 UTC, dalonsod approved these changes

2024-06-26 12:15 UTC, merged