[13.0][IMP] logistics_planning_base: draft button
solvosci/slv-stock pull request #148
Opened 2024-09-19 07:26 UTC by ChristianSantamaria

- New button Mark as Draft
- Adds new icons in state buttons

2024-09-19 08:39 UTC, ChristianSantamaria commented
@dalonsod Installed in test enviroment, can u review?

2024-09-19 14:57 UTC, dalonsod requested changes
See comments, when attended, I'll test it ASAP

2024-09-19 14:57 UTC, dalonsod commented on logistics_planning_invoicing/__manifest__.py
> +    'version': '13.0.2.2.0',
These changes should be applied in `logistics_planning_base` manifest file.

2024-09-19 14:57 UTC, dalonsod commented on logistics_planning_base/views/logistics_schedule_views.xml
> +                        attrs="{'invisible': [('state', '=', 'draft')]}"
Desired flow for `draft` state as destination is only from `cancel` state:
```suggestion
                        attrs="{'invisible': [('state', '!=', 'cancel')]}"
```

2024-09-19 14:57 UTC, dalonsod commented on logistics_planning_base/models/logistics_schedule.py
> +        to_draft = self.filtered(lambda x: x.state in ['ready', 'done', 'cancel'])
Desired flow for `draft` state as destination is only from `cancel` state:
```suggestion
        to_draft = self.filtered(lambda x: x.state == 'cancel')
```

2024-09-20 07:37 UTC, ChristianSantamaria commented
@dalonsod updated and tested in test enviroment :+1:

2024-09-20 08:48 UTC, dalonsod approved these changes
Tested :+1:

2024-09-20 08:48 UTC, merged