[13.0][IMP] logistics_planning_*: some improvements
solvosci/slv-stock pull request #156
Opened 2024-11-29 12:24 UTC by ChristianSantamaria

The first 3 commits:
Adds hook and unhook logistics with account move line

Other:
Adds wizard to confirm the cancellation of logistic schedule

2024-12-04 18:29 UTC, dalonsod commented on logistics_planning_invoicing/wizards/logistics_schedule_existing_account_move_wizard.py
> +            record.domain_invoice_line_id = self.env['account.move.line'].search([('move_id.partner_id', '=', record.carrier_id.id), ('product_id', '=', product_id.id)])
Could you hook the domain part? When done, we'll be able to inject from sales and purchase logistics addons and extra condition regarding to matching analytic account (that comes from order line linked to the logistics schedule).

2024-12-09 11:03 UTC, ChristianSantamaria commented
@dalonsod can u review this?

2024-12-09 11:15 UTC, dalonsod commented
Not sure if current implementation for sales and purchase addons will work when analytic account is not filled in origin (an unexpected error could be raised, looking for `id` value). And remember, for such case (logistics planning has no analytic account linked) we need to find those invoice lines that have no analytic account filled as well.

2024-12-09 11:17 UTC, dalonsod commented on logistics_planning_invoicing/wizards/logistics_schedule_existing_account_move_wizard.py
> +    domain_invoice_line_id = fields.Many2many('account.move.line', compute='_compute_domain_invoice_line_id')
Better naming:
```suggestion
    domain_invoice_line_ids = fields.Many2many('account.move.line', compute='_compute_domain_invoice_line_ids')
```

2024-12-09 11:23 UTC, dalonsod commented on logistics_planning_invoicing/wizards/logistics_schedule_existing_account_move_wizard.py
> +        return [('move_id.partner_id', '=', self.carrier_id.id), ('product_id', '=', product_id.id)]
I miss a default condition: only select those move lines that actually are invoice lines (see https://github.com/odoo/odoo/blob/4cc086d330b73514fbc64a7fcf22d8a7a9f1b691/addons/account/models/account_move.py#L216)

2024-12-18 07:25 UTC, ChristianSantamaria commented
@dalonsod done

2024-12-19 11:54 UTC, ChristianSantamaria commented
Already in test enviroment

2024-12-19 13:15 UTC, ChristianSantamaria commented
@dalonsod i take advantage of this PR, added the cancellation wizard

2024-12-19 13:15 UTC, ChristianSantamaria commented
And test enviroment updated

2024-12-19 14:48 UTC, dalonsod commented
Regarding to cancel with confirmation flow I see too duplicated code. We'll see it together and try to find a better implementation.

2025-01-14 08:45 UTC, dalonsod commented
@ChristianSantamaria could you make a rebase with `origin/13.0`? I've recently merged #159

2025-01-20 16:52 UTC, dalonsod approved these changes
See only minor comments, once done I'll propose customer installing this without waiting for invoice unassingment functionality

2025-01-20 16:52 UTC, dalonsod commented on logistics_planning_invoicing/wizards/logistics_schedule_existing_account_move_wizard_views.xml
> +                        <button name="add_invoice" string="Add Existing Invoice" type="object" class="oe_highlight"/>
Better this:
```suggestion
                        <button name="add_invoice" string="Add to Existing Invoice" type="object" class="oe_highlight"/>
```
And then, for `es` translation, the right text should be "Añadir **_a_** factura existente".

2025-01-20 16:52 UTC, dalonsod commented on logistics_planning_invoicing/wizards/logistics_schedule_existing_account_move_wizard_views.xml
> +                        <field name="invoice_line_id"
When selecting this combobox, create and edit options should be disabled.

2025-01-20 16:52 UTC, dalonsod commented on logistics_planning_invoicing/views/logistics_schedule_views.xml
> +                    icon="fa-pencil-square-o"
Add this (this should be added to existing button as well, IMO...):
```suggestion
                    icon="fa-pencil-square-o"
                    groups="account.group_account_invoice"
```

2025-01-21 06:53 UTC, ChristianSantamaria commented
@dalonsod Done, updated in test enviroment

2025-01-25 08:30 UTC, dalonsod requested changes
Only code review, see comments

2025-01-25 08:30 UTC, dalonsod commented on logistics_planning_invoicing/models/logistics_schedule.py
> +            raise ValidationError(_('There are different carriers on the selected schedules or there is no carrier.'))
We should add more restrictions (the same for "Add to existing invoice" form button invisible domain):
* Action shouldn't be accessible by non-account users => is it possible to directly add this restriction to action definition, rather than a python check?
* Schedule must be marked as invoiceable.
* Schedule shouldn't be marked as done neither linked to an invoice line.

And also those restrictions added for "Create new invoice" batch process (stock move filled, has quantity, is finished):
https://github.com/solvosci/slv-stock/blob/5cf2bb953793884af7a91fbe8c3f946fe740a3fb/logistics_planning_invoicing/models/logistics_schedule.py#L121-L129

2025-01-25 08:30 UTC, dalonsod commented on logistics_planning_invoicing/wizards/logistics_schedule_existing_account_move_wizard_views.xml
> +                        <field name="invoice_line_id"
I've realized that it could be more usable splitting this selection in two steps:
* First, user selects the target invoice (so it's possible to search across invoice number in a very simple way). The invoice Many2one field is filtered by journal and carrier.
* Second, once invoice is selected, we enable invoice line selection, that is filtered by invoice (and exclude for tab), a simpler filter. This field will be only available to be selected when invoice is filled, and we'll keep current display name format.

With these improvements there's no longer need of custom domain field nor invoice line `name_search`.

What do you think?

2025-01-25 08:50 UTC, dalonsod commented on logistics_planning_invoicing/__manifest__.py
> +    'version': '13.0.2.1.1',
And fix this bump version:
```suggestion
    'version': '13.0.2.1.0',
```

2025-01-27 09:10 UTC, ChristianSantamaria commented
@dalonsod Done, i keep the name_get for better visualization
![imagen](https://github.com/user-attachments/assets/6286923e-aeb2-4943-b565-cd6c2ffcb4bc)

2025-01-27 09:11 UTC, ChristianSantamaria commented
And updated in test enviroment :+1:

2025-01-27 15:13 UTC, dalonsod approved these changes
:+1:

2025-01-27 15:13 UTC, merged