13.0 add stock picking security
solvosci/slv-stock pull request #5
Opened 2021-02-10 16:52 UTC by ChristianSantamaria

Add a group with reduced permissions for partners in Stock.

2021-02-10 17:32 UTC, dalonsod requested changes
See comment. And commit history is not in a proper way yet, but it could be fixed later, don't worry

2021-02-10 17:32 UTC, dalonsod commented on stock_picking_security/security/stock_security.xml
> +            <field name="implied_ids" eval="[(6, 0, [ref('stock_picking_security.group_stock_picking_partner'), ref('account.group_account_invoice')])]"/>
Tried to install, faced an error:
```
"External ID not found in the system: account.group_account_invoice" while evaluating
"[(6, 0, [ref('stock_picking_security.group_stock_picking_partner'), ref('account.group_account_invoice')])]
```
And that's right, making this addon depending on `stock`, `account` addon shouldn't be used.

You'd get the desired behavior changing this (maybe you should test it and check if `account` permissions are kept):

```suggestion
            <field name="implied_ids" eval="[(4,ref('stock_picking_security.group_stock_picking_partner'))]"/>
```

2021-02-10 17:46 UTC, dalonsod commented
@lmiguens-solvos what do you think about addon name (`stock_picking_security`)?

2021-02-11 08:05 UTC, lmiguens-solvos commented
> @lmiguens-solvos what do you think about addon name (`stock_picking_security`)?

Well, it is not very explicit about what it provides at the security level... does not indicate that I will only have permission for operations in my warehouses
But it may be too long to put something like: stock_picking_my_warehouses_restriction_security ??

2021-02-11 08:14 UTC, dalonsod commented
Well, I'd focus to `picking` term. The current changes are the following:
- The `Inventory` group hierarchy is changed: there's a new group inserted between `Users` a `Administrator` groups.
- `User` group now has lost several menu accesses, those ones are moved to `Administrator` group.

These changes have an scope greater than picking operations. Thus, we're redefining stock security schema a little bit...

2021-02-17 10:06 UTC, lmiguens-solvos commented
> Well, I'd focus to `picking` term. The current changes are the following:
> 
> * The `Inventory` group hierarchy is changed: there's a new group inserted between `Users` a `Administrator` groups.
> * `User` group now has lost several menu accesses, those ones are moved to `Administrator` group.
> 
> These changes have an scope greater than picking operations. Thus, we're redefining stock security schema a little bit...

ok, perhaps a name like stock_inventory_security would be better??

2021-02-17 10:15 UTC, lmiguens-solvos requested changes
- It is also necessary to add access to the menu "Reports" -> "Inventory report" to make inventory adjustments from there
- Also add that this user can see the operations of the contact parent_id (user contact parent_id warehouse operations)

2021-02-17 12:58 UTC, dalonsod commented
> ok, perhaps a name like stock_inventory_security would be better??

`inventory` and `stock` are synonyms, at least in Odoo... maybe simply `stock_security`?

2021-02-17 15:11 UTC, lmiguens-solvos commented
> > ok, perhaps a name like stock_inventory_security would be better??
> 
> `inventory` and `stock` are synonyms, at least in Odoo... maybe simply `stock_security`?



> > ok, perhaps a name like stock_inventory_security would be better??
> 
> `inventory` and `stock` are synonyms, at least in Odoo... maybe simply `stock_security`?

And something more extensive that indicates the limitation introduced with this addon? 
something like stock_warehouse_partner_limited_security

2021-02-17 15:18 UTC, dalonsod commented
> And something more extensive that indicates the limitation introduced with this addon?
> something like stock_warehouse_partner_limited_security

OK, I propose `stock_warehouse_partner_security`, without "limited" :-)

Maybe this addon should be improved in the future with more groups with other requisites, but not right now.

2021-02-23 18:10 UTC, closed without merging

2021-02-23 18:20 UTC, dalonsod commented
Closed and re-opened in #8